config/routes.rb
Rails.application.routes.draw do
  root 'prototypes#index'
  devise_for :users
  resources :users, only: [:edit, :show, :update]
  namespace :prototypes do
    resources :newest, only: :index
  end
  resources :prototypes do
    resources :likes, only: [:create, :destroy], module: 'prototypes'
    resources :comments, only: :create, module: 'prototypes'
  end
  resources :tags, only: [:index, :show]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :prototype, counter_cache: :comments_count
  belongs_to :user
  validates :content, presence: true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :prototype, counter_cache: :likes_count
  belongs_to :user
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :prototype
  enum status: { main: 0, sub: 1 }
  mount_uploader :content, ImageUploader
  validates_presence_of :status
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :photos, reject_if: proc { |attributes| attributes['content'].blank? }
  acts_as_taggable
  validates :title, :catch, :concept, presence: true

  def liked_user?(user)
   likes.find_by(user_id: user)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :prototypes
  has_many :likes
  has_many :comments
  mount_uploader :avatar, ImageUploader
  validates :username, :email, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar, :member, :profile, :works])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    Comment.create(comment_params)
    @comment = Comment.new
    @comments = Comment.where(prototype_id: params[:prototype_id])
    @prototype = Prototype.find(params[:prototype_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:id, :content).merge(user_id: current_user.id, prototype_id: params[:prototype_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(user_id: current_user.id, prototype_id: params[:prototype_id])
    @likes = Like.where(prototype_id: params[:prototype_id])
    @prototype = Prototype.find(params[:prototype_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, prototype_id: params[:prototype_id])
    like.destroy
    @likes = Like.where(prototype_id: params[:prototype_id])
    @prototype = Prototype.find(params[:prototype_id])
  end
end

app/controllers/prototypes/comments_controller.rb
class Prototypes::CommentsController < ApplicationController
  def create
    Comment.create(comment_params)
    @comment = Comment.new
    @comments = Comment.where(prototype_id: params[:prototype_id])
    @prototype = Prototype.find(params[:prototype_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:id, :content).merge(user_id: current_user.id, prototype_id: params[:prototype_id])
  end
end

app/controllers/prototypes/likes_controller.rb
class Prototypes::LikesController < ApplicationController
  def create
    @like = Like.create(user_id: current_user.id, prototype_id: params[:prototype_id])
    @likes = Like.where(prototype_id: params[:prototype_id])
    @prototype = Prototype.find(params[:prototype_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, prototype_id: params[:prototype_id])
    like.destroy
    @likes = Like.where(prototype_id: params[:prototype_id])
    @prototype = Prototype.find(params[:prototype_id])
  end
end

app/controllers/prototypes/newest_controller.rb
class Prototypes::NewestController < ApplicationController
  def index
    @prototype = Prototype.includes(:photos).order("created_at DESC").page(params[:page]).per(12)
    render "prototypes/index"
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :set_prototype, only: [:edit, :show, :update, :destroy]

  def index
    @prototype = Prototype.includes(:photos).order("likes_count DESC").page(params[:page]).per(12)
  end

  def new
    @prototype = Prototype.new
    @prototype.photos.build
  end

  def create
    @prototype = Prototype.create(prototype_params)
    if @prototype.save
      flash[:notice] = "投稿が成功しました"
      redirect_to root_path
    else
      flash[:notice] = "入力内容が正しくありません"
      render :new
    end
  end

  def show
    @like = @prototype.likes(params[:id])
    @likes = @prototype.likes_count
    @comment = Comment.new
    @comments = @prototype.comments_count
  end

  def edit
    @subphotos = @prototype.photos.sub
    (2 - @subphotos.count).times { @subphotos << @prototype.photos.build(status: "sub") }
  end

  def update
    if @prototype.update(prototype_params)
      flash[:notice] = "編集が成功しました"
      redirect_to root_path
    else
      flash[:notice] = "入力内容が正しくありません"
      render :edit
    end
  end

  def destroy
    if @prototype.destroy
      flash[:notice] = "削除しました"
      redirect_to root_path
    else
      flash[:notice] = "入力内容が正しくありません"
      render :show
    end
  end

  private

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end


  def prototype_params
    params.require(:prototype).permit(:id, :title, :catch, :concept, photos_attributes: [:id, :prototype_id, :content, :status]).merge(user_id: current_user.id, tag_list: params[:prototype][:tag])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.most_used
  end

  def show
    @tag = ActsAsTaggableOn::Tag.find(params[:id])
    @prototypes = Prototype.tagged_with(@tag.name).includes(:photos).order("created_at DESC")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :show, :update]

  def edit
  end

  def show
    @prototypes = @user.prototypes.includes(:photos).order("created_at DESC").page(params[:page]).per(8)
  end

  def update
    if @user.update(update_params)
      bypass_sign_in @user
      flash[:notice] = "編集が成功しました"
      redirect_to root_path
    else
      flash[:notice] = "入力内容が正しくありません"
      render :edit
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def update_params
    params.require(:user).permit(:id, :username, :email, :password, :avatar, :member, :profile, :works)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def active?(contoroller_name)
    return "active" if contoroller_name == params[:controller]
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.
  

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/")
      = image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px")
    .navbar-collapse.collapse.navbar-responsive-collapse
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", href: "#", role: "button"}
              = current_user.username
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to "My Page", user_path(current_user.id), method: :get
              %li
                = link_to "Profile Edit", edit_user_path(current_user), method: :get
              %li
                = link_to "Logout", destroy_user_session_path, method: :delete
          %li
            .btn.btn-primary.navbar-btn
              = link_to "New Proto",new_prototype_path, method: :get
      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to "Get Started", new_user_session_path, method: :get

app/views/layouts/_messages.html.haml
- flash.each do |key, value|
  %div{class: "alert alert-#{key}"}
    %a.close{"data-dismiss" => "alert", href: "#"} ×
    %ul
      %li
        = value

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" => "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    = render 'layouts/messages'
    = yield
    = render "layouts/footer"

app/views/prototypes/_like.html.haml
- if user_signed_in?
  - if prototype.liked_user?(current_user)
    = button_to prototype_like_path(prototype, like), method: :delete, class: "btn btn-default increment-botton", id: "unlike-button", remote: true do
      = image_tag("icon_red_heart.svg")
      %span.num#like-sum
        Like
        = prototype.likes.count
  - else
    = button_to prototype_likes_path(prototype), method: :post, class: "btn btn-default increment-botton", id: "like-button", remote: true do
      = image_tag("icon_heart.svg")
      %span.num#like-sum
        Like
        = prototype.likes.count
- else
  = image_tag("icon_heart.svg")
  %span
    = prototype.likes.count

app/views/prototypes/comments/_comment.html.haml
.row.proto-comments
  %h4.col-md-12
    Comments
    %span.num (#{prototype.comments.count})
  .col-md-8
    - prototype.comments.each do |comment|
      .media
        .media-left
          = link_to user_path(comment.user) do
            = image_tag comment.user.avatar, alt: "64x64", "data-holder-rendered": "true", "data-src": "holder.js/64x64", style: "width: 64px; height: 64px;", class: "media-object"
        .media-body
          %h4#top-aligned-media.media-heading
            = comment.user.username
            %a.anchorjs-link{href: "#top-aligned-media"}
              %span.anchorjs-icon
          %p
            = comment.content
    - if user_signed_in?
      = form_for( [prototype, comment], html: {class: "form-inline"}, remote: true ) do |f|
        %h4 Write a comment
        .row
          .form-group.col-md-10
            = f.text_area :content, placeholder: "Your comments", rows: "3", class: "form-control"
          .form-group.col-md-2
            = f.submit "Comment", class: "button btn btn-primary"

app/views/prototypes/comments/create.js.haml
$("#comments").html("#{ j(render partial: 'prototypes/comments/comment', locals: { prototype: @prototype, comments: @comments, comment: @comment})}");

app/views/prototypes/edit.html.haml
= form_for(@prototype, html: {class: "container proto-new"} ) do |f|
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        = f.text_field :title, autofocus: true, placeholder: "Title", class: "proto-new-title"
    .row
      .col-md-12
        .cover-image-upload.js-preview{:style => "background-image: url(#{@prototype.photos.main.first.content}); background-size: contain;"}
          = f.fields_for :photos, @prototype.photos.main.first do |photo|
            = photo.file_field :content, class: "js-image"
            = photo.hidden_field :status, value: :main
      .col-md-12
        %ul.proto-sub-list.list-group
          - @subphotos.each do |s|
            %li.list-group-item.col-md-4
              - if s.id
                .image-upload.js-preview{:style => "background-image: url(#{s.content}); background-size: contain;"}
                  = f.fields_for :photos, s do |photo|
                    = photo.file_field :content, class: "js-image"
                    = photo.hidden_field :status, value: :sub
              - else
                .image-upload.js-preview
                  = f.fields_for :photos, s do |photo|
                    = photo.file_field :content, class: "js-image"
                    = photo.hidden_field :status, value: :sub
          %li.list-group-item.col-md-4
            .image-upload-plus
              %span +
    .row.proto-description
      .col-md-12
        = f.text_field :catch, autofocus: true, placeholder: "Catch Copy"
      .col-md-12
        = f.text_area :concept, autofocus: true, cols: "30", rows: "4", placeholder: "Concept"
      .col-md-12
        %h4 Tag List
        .row
          .col-md-3
            = text_field_tag "prototype[tag][]", "", placeholder: "Web Design", value: @prototype.tags.first
          .col-md-3
            = text_field_tag "prototype[tag][]", "", placeholder: "UI", value: @prototype.tags.second
          .col-md-3
            = text_field_tag "prototype[tag][]", "", placeholder: "Application", value: @prototype.tags.third
    .row.text-center.proto-btn
      = f.submit "Publish", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li{class: active?("prototypes"), role: "presentation"}
          = link_to "Popular PROTO", root_path
        %li{class: active?("prototypes/newest"), role: "presentation"}
          = link_to "Newest PROTO", prototypes_newest_index_path
      = link_to "View Tags", tags_path, type: 'button', class: "btn btn-default col-lg-1"
.container.proto-list
  .row
    - @prototype.each do |p|
      .col-sm-4.col-md-3.proto-content
        .thumbnail
          = link_to prototype_path(p.id) do
            = image_tag p.photos.main.first.content
            .caption
              %h3
                = p.title
              .proto-meta
                .proto-user
                  = link_to "by #{p.user.username}", user_path(p.user.id)
                .proto-posted
                  = p.created_at.strftime("%b %d")
              %ul.proto-tag-list.list-inline
                - p.tags.each do |prototypetag|
                  %li
                    =link_to prototypetag.name, tag_path(prototypetag.id), class: "btn btn-default"
.text-center
  = paginate @prototype

app/views/prototypes/likes/_like.html.haml
- if user_signed_in?
  - if prototype.liked_user?(current_user)
    = button_to prototype_like_path(prototype, like), method: :delete, class: "btn btn-default increment-botton", remote: true do
      = image_tag("icon_red_heart.svg")
      %span.num#like-sum
        Like
        = prototype.likes.count
  - else
    = button_to prototype_likes_path(prototype), method: :post, class: "btn btn-default increment-botton", remote: true do
      = image_tag("icon_heart.svg")
      %span.num#like-sum
        Like
        = prototype.likes.count
- else
  %button.btn.btn-default.increment-botton
    = image_tag("icon_heart.svg")
    %span.num#like-sum
      Like
      = prototype.likes.count

app/views/prototypes/likes/create.js.haml
$("#like-button").html("#{ j(render partial: 'prototypes/likes/like', locals: { prototype: @prototype, likes: @likes, like: @like })}");

app/views/prototypes/likes/destroy.js.haml
$("#like-button").html("#{ j(render partial: 'prototypes/likes/like', locals: { prototype: @prototype, likes: @likes })}");

app/views/prototypes/new.html.haml
= form_for(@prototype, html: {class: "container proto-new"} ) do |f|
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        = f.text_field :title, autofocus: true, placeholder: "Title", class: "proto-new-title"
    .row
      .col-md-12
        .cover-image-upload.js-preview
          = f.fields_for :photos do |photo|
            = photo.file_field :content, class: "js-image"
            = photo.hidden_field :status, value: :main
      .col-md-12
        %ul.proto-sub-list.list-group
          %li.list-group-item.col-md-4
            .image-upload.js-preview
              = f.fields_for :photos do |photo|
                = photo.file_field :content, class: "js-image"
                = photo.hidden_field :status, value: :sub
          %li.list-group-item.col-md-4
            .image-upload.js-preview
              = f.fields_for :photos do |photo|
                = photo.file_field :content, class: "js-image"
                = photo.hidden_field :status, value: :sub
          %li.list-group-item.col-md-4
            .image-upload-plus
              %span +
    .row.proto-description
      .col-md-12
        = f.text_field :catch, autofocus: true, placeholder: "Catch Copy"
      .col-md-12
        = f.text_area :concept, autofocus: true, cols: "30", rows: "4", placeholder: "Concept"
      .col-md-12
        %h4 Tag List
        .row
          .col-md-3
            = text_field_tag "prototype[tag][]", "", placeholder: "Web Design"
          .col-md-3
            = text_field_tag "prototype[tag][]", "", placeholder: "UI"
          .col-md-3
            = text_field_tag "prototype[tag][]", "", placeholder: "Application"
    .row.text-center.proto-btn
      = f.submit "Publish", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to user_path(@prototype.user) do
            = image_tag @prototype.user.avatar, alt: "64x64", "data-holder-rendered": "true", "data-src": "holder.js/64x64", style: "width: 64px; height: 64px;", class: "media-object"
        .media-body
          %h4#top-aligned-media.media-heading
            Top aligned media
          .proto-user
            = link_to "by #{@prototype.user.username}", user_path(@prototype.user)
            %span.degree #{@prototype.user.profile} #{@prototype.user.member}
    .col-md-6.text-right
      #like-button
        = render partial: 'prototypes/likes/like', locals: { prototype: @prototype, likes: @likes, like: @like}
  .row
    .col-md-9
      = image_tag @prototype.photos.main.first.content, class: 'img-responsive'
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.photos.sub.each do |s|
          %li.list-group-item
            = image_tag s.content, class: 'img-responsive'
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.catch
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        - @prototype.tags.each do |prototypetag|
          %li
            =link_to prototypetag.name, tag_path(prototypetag.id), class: "btn btn-default"
  #comments
    = render partial: 'prototypes/comments/comment', locals: { prototype: @prototype, comments: @comments, comment: @comment}

app/views/tags/index.html.haml
.container
  .row
    - @tags.each do |tag|
      .col-sm-4.col-sm-3
        = link_to tag_path(tag.id), class: "tag thumbnail" do
          .tag-name
            = tag.name
          .tag-project
            = "#{tag.taggings_count} project"

app/views/tags/show.html.haml
.container
  .row
    .tag-header
      %span
        = "# #{@tag.name}"
    - @prototypes.each do |p|
      .col-sm-4.col-md-3.proto-content
        .thumbnail
          = link_to prototype_path(p) do
            = image_tag p.photos.main.first.content
          .caption
            %h3
              = p.title
            .proto-meta
              .proto-user
                = link_to "by #{p.user.username}", user_path(p.user)
              .proto-posted
                = p.created_at.strftime("%b %d")

app/views/users/edit.html.haml
= form_for(current_user, html: {class: "container user-new"} ) do |f|
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        %h2 Edit Profile
        .user-name_image.row
          .user-name.col-md-10
            = f.text_field :username, autofocus: true, placeholder: "Username", value: current_user.username
          .user-image.col-md-2.js-preview{:style => "background-image: url(#{current_user.avatar}); background-size: contain;"}
            %button.btn.btn-primary Change image
            = f.file_field :avatar, class: "js-image"
        = f.email_field :email, autofocus: true, placeholder: "E-Mail", class: "user-email", value: current_user.email
        = f.password_field :password, autocomplete: "off", placeholder: "Password", class: "user-password"
      .col-md-12
        %h4 Member of
        .user-user-member.row
          .user-name.col-md-12
            = f.text_field :member, autofocus: true, placeholder: "Member", value: current_user.member
        %h4 Profile
        .user-user-profile.row
          .user-name.col-md-12
            = f.text_area :profile, autofocus: true, cols: "30", rows: "4", placeholder: "Profile" do
              = current_user.profile
        %h4 Works
        .user-name_image.row
          .user-name.col-md-12
            = f.text_area :works, autofocus: true, cols: "30", rows: "4", placeholder: "Works" do
              = current_user.works
    .row.text-center.user-btn
      = f.submit "Save", class: "btn btn-lg btn-primary btn-block"

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        = link_to user_path(@user.id) do
          = image_tag @user.avatar, alt: "64x64", "data-holder-rendered": "true", "data-src": "holder.js/64x64", style: "width: 64px; height: 64px;", class: "media-object"
      .media-body
        %h4#top-aligned-media.media-heading
          Top aligned media
          %span.label.label-default.project-number
            = @user.prototypes.count
            %i Projects
        .proto-user
          %span.degree
            = @user.member
        .row
          .col-md-6
            %h4 Profile
            %p
              = @user.profile
          .col-md-6
            %h4 Works
            %p
              = @user.works
.container.proto-list
  .row
    - @prototypes.each do |prototype|
      .col-sm-4.col-md-3.proto-content
        .dropdown.drop_menu_location
          = button_tag type: 'button', "aria-expanded": "true", "data-toggle": "dropdown", class: "btn btn-default dropdown-toggle", id: "dropdownMenu" do
            Action
          %ul.dropdown-menu{"aria-labelledby": "dropdownMenu1"}
            %li
              = link_to "Delete", prototype_path(prototype), :method => :delete
            %li
              = link_to "Edit", edit_prototype_path(prototype)
        .thumbnail
          = link_to prototype_path(prototype.id) do
            = image_tag prototype.photos.main.first.content
            .caption
              %h3
                = prototype.title
              .proto-meta
                .proto-user
                  = link_to "by #{@user.username}", user_path(@user.id)
                .proto-posted
                  = prototype.created_at.strftime("%b %d")
              %ul.proto-tag-list.list-inline
                - prototype.tags.each do |tag|
                  %li
                    = link_to "#{tag.name}", 'tag_path(tag.id)', class: 'btn btn-default'
.text-center
  = paginate @prototypes